# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11integration.proto\x12\x05unary\"G\n\x19RegisterIntegrationParams\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0b\n\x03ids\x18\x03 \x03(\x05\"-\n\x19RegisterIntegrationReturn\x12\x10\n\x08numOfIds\x18\x04 \x01(\x05\"\x17\n\tGetParams\x12\n\n\x02id\x18\x05 \x01(\x05\"*\n\tGetReturn\x12\x0f\n\x07\x61\x64\x64ress\x18\x06 \x01(\t\x12\x0c\n\x04port\x18\x07 \x01(\x05\"\x12\n\x10StopServerParams\"$\n\x10StopServerReturn\x12\x10\n\x08numOfIds\x18\x08 \x01(\x05\x32\xd9\x01\n\x0bIntegration\x12[\n\x13RegisterIntegration\x12 .unary.RegisterIntegrationParams\x1a .unary.RegisterIntegrationReturn\"\x00\x12+\n\x03Get\x12\x10.unary.GetParams\x1a\x10.unary.GetReturn\"\x00\x12@\n\nStopServer\x12\x17.unary.StopServerParams\x1a\x17.unary.StopServerReturn\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'integration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERINTEGRATIONPARAMS._serialized_start=28
  _REGISTERINTEGRATIONPARAMS._serialized_end=99
  _REGISTERINTEGRATIONRETURN._serialized_start=101
  _REGISTERINTEGRATIONRETURN._serialized_end=146
  _GETPARAMS._serialized_start=148
  _GETPARAMS._serialized_end=171
  _GETRETURN._serialized_start=173
  _GETRETURN._serialized_end=215
  _STOPSERVERPARAMS._serialized_start=217
  _STOPSERVERPARAMS._serialized_end=235
  _STOPSERVERRETURN._serialized_start=237
  _STOPSERVERRETURN._serialized_end=273
  _INTEGRATION._serialized_start=276
  _INTEGRATION._serialized_end=493
# @@protoc_insertion_point(module_scope)
