# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import integration_pb2 as integration__pb2


class IntegrationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterIntegration = channel.unary_unary(
                '/unary.Integration/RegisterIntegration',
                request_serializer=integration__pb2.RegisterIntegrationParams.SerializeToString,
                response_deserializer=integration__pb2.RegisterIntegrationReturn.FromString,
                )
        self.Get = channel.unary_unary(
                '/unary.Integration/Get',
                request_serializer=integration__pb2.GetParams.SerializeToString,
                response_deserializer=integration__pb2.GetReturn.FromString,
                )
        self.StopServer = channel.unary_unary(
                '/unary.Integration/StopServer',
                request_serializer=integration__pb2.StopServerParams.SerializeToString,
                response_deserializer=integration__pb2.StopServerReturn.FromString,
                )


class IntegrationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterIntegration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntegrationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterIntegration': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterIntegration,
                    request_deserializer=integration__pb2.RegisterIntegrationParams.FromString,
                    response_serializer=integration__pb2.RegisterIntegrationReturn.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=integration__pb2.GetParams.FromString,
                    response_serializer=integration__pb2.GetReturn.SerializeToString,
            ),
            'StopServer': grpc.unary_unary_rpc_method_handler(
                    servicer.StopServer,
                    request_deserializer=integration__pb2.StopServerParams.FromString,
                    response_serializer=integration__pb2.StopServerReturn.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unary.Integration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Integration(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterIntegration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Integration/RegisterIntegration',
            integration__pb2.RegisterIntegrationParams.SerializeToString,
            integration__pb2.RegisterIntegrationReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Integration/Get',
            integration__pb2.GetParams.SerializeToString,
            integration__pb2.GetReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Integration/StopServer',
            integration__pb2.StopServerParams.SerializeToString,
            integration__pb2.StopServerReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
