# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protofiles/database.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protofiles/database.proto\x12\x05unary\">\n\x0cInsertParams\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02\"\x1f\n\x0cInsertReturn\x12\x0f\n\x07\x65xisted\x18\x04 \x01(\x05\"\x17\n\tGetParams\x12\n\n\x02id\x18\x05 \x01(\x05\"/\n\tGetReturn\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\r\n\x05value\x18\x07 \x01(\x02\"%\n\x10StopServerReturn\x12\x11\n\tnumOfKeys\x18\x08 \x01(\x05\"\x12\n\x10StopServerParams\"/\n\x0eRegisterParams\x12\x0f\n\x07\x61\x64\x64ress\x18\t \x01(\t\x12\x0c\n\x04port\x18\n \x01(\x05\"#\n\x0fRegisterReturns\x12\x10\n\x08numOfIds\x18\x0b \x01(\x05\x32\xec\x01\n\x08\x44\x61tabase\x12\x34\n\x06Insert\x12\x13.unary.InsertParams\x1a\x13.unary.InsertReturn\"\x00\x12+\n\x03Get\x12\x10.unary.GetParams\x1a\x10.unary.GetReturn\"\x00\x12@\n\nStopServer\x12\x17.unary.StopServerParams\x1a\x17.unary.StopServerReturn\"\x00\x12;\n\x08Register\x12\x15.unary.RegisterParams\x1a\x16.unary.RegisterReturns\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protofiles.database_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSERTPARAMS._serialized_start=36
  _INSERTPARAMS._serialized_end=98
  _INSERTRETURN._serialized_start=100
  _INSERTRETURN._serialized_end=131
  _GETPARAMS._serialized_start=133
  _GETPARAMS._serialized_end=156
  _GETRETURN._serialized_start=158
  _GETRETURN._serialized_end=205
  _STOPSERVERRETURN._serialized_start=207
  _STOPSERVERRETURN._serialized_end=244
  _STOPSERVERPARAMS._serialized_start=246
  _STOPSERVERPARAMS._serialized_end=264
  _REGISTERPARAMS._serialized_start=266
  _REGISTERPARAMS._serialized_end=313
  _REGISTERRETURNS._serialized_start=315
  _REGISTERRETURNS._serialized_end=350
  _DATABASE._serialized_start=353
  _DATABASE._serialized_end=589
# @@protoc_insertion_point(module_scope)
