# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protofiles/integration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotofiles/integration.proto\x12\x05unary\"G\n\x19RegisterIntegrationParams\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0b\n\x03ids\x18\x03 \x03(\x05\"-\n\x19RegisterIntegrationReturn\x12\x10\n\x08numOfIds\x18\x04 \x01(\x05\"\"\n\x14GetIntegrationParams\x12\n\n\x02id\x18\x05 \x01(\x05\"5\n\x14GetIntegrationReturn\x12\x0f\n\x07\x61\x64\x64ress\x18\x06 \x01(\t\x12\x0c\n\x04port\x18\x07 \x01(\x05\"\x1d\n\x1bStopIntegrationServerParams\"/\n\x1bStopIntegrationServerReturn\x12\x10\n\x08numOfIds\x18\x08 \x01(\x05\x32\x9b\x02\n\x0bIntegration\x12[\n\x13RegisterIntegration\x12 .unary.RegisterIntegrationParams\x1a .unary.RegisterIntegrationReturn\"\x00\x12L\n\x0eGetIntegration\x12\x1b.unary.GetIntegrationParams\x1a\x1b.unary.GetIntegrationReturn\"\x00\x12\x61\n\x15StopIntegrationServer\x12\".unary.StopIntegrationServerParams\x1a\".unary.StopIntegrationServerReturn\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protofiles.integration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERINTEGRATIONPARAMS._serialized_start=39
  _REGISTERINTEGRATIONPARAMS._serialized_end=110
  _REGISTERINTEGRATIONRETURN._serialized_start=112
  _REGISTERINTEGRATIONRETURN._serialized_end=157
  _GETINTEGRATIONPARAMS._serialized_start=159
  _GETINTEGRATIONPARAMS._serialized_end=193
  _GETINTEGRATIONRETURN._serialized_start=195
  _GETINTEGRATIONRETURN._serialized_end=248
  _STOPINTEGRATIONSERVERPARAMS._serialized_start=250
  _STOPINTEGRATIONSERVERPARAMS._serialized_end=279
  _STOPINTEGRATIONSERVERRETURN._serialized_start=281
  _STOPINTEGRATIONSERVERRETURN._serialized_end=328
  _INTEGRATION._serialized_start=331
  _INTEGRATION._serialized_end=614
# @@protoc_insertion_point(module_scope)
